export const fake_data = [
  {
    id: "INT1336",
    group: "07",
    name: "Mạng máy tính",
    stc: "3",
    result_end: "7.0",
    score_10: "7.8",
    score_4: "3",
    score_c: "B",
  },
  {
    id: "INT1336",
    group: "07",
    name: "Mạng máy tính",
    stc: "3",
    result_end: "7.0",
    score_10: "7.8",
    score_4: "3",
    score_c: "B",
  },
  {
    id: "INT1336",
    group: "07",
    name: "Mạng máy tính",
    stc: "3",
    result_end: "7.0",
    score_10: "7.8",
    score_4: "3",
    score_c: "B",
  },
  {
    id: "INT1336",
    group: "07",
    name: "Mạng máy tính",
    stc: "3",
    result_end: "7.0",
    score_10: "7.8",
    score_4: "3",
    score_c: "B",
  },
  {
    id: "INT1336",
    group: "07",
    name: "Mạng máy tính",
    stc: "3",
    result_end: "7.0",
    score_10: "7.8",
    score_4: "3",
    score_c: "B",
  },
];
